# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/jonat/OneDrive/Documents/pure_doom

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/jonat/OneDrive/Documents/pure_doom

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/jonat/OneDrive/Documents/pure_doom/CMakeFiles /mnt/c/Users/jonat/OneDrive/Documents/pure_doom//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/jonat/OneDrive/Documents/pure_doom/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cuda_objects

# Build rule for target.
cuda_objects: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cuda_objects
.PHONY : cuda_objects

# fast build rule for target.
cuda_objects/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuda_objects.dir/build.make CMakeFiles/cuda_objects.dir/build
.PHONY : cuda_objects/fast

#=============================================================================
# Target rules for targets named common_cpp_objects

# Build rule for target.
common_cpp_objects: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 common_cpp_objects
.PHONY : common_cpp_objects

# fast build rule for target.
common_cpp_objects/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common_cpp_objects.dir/build.make CMakeFiles/common_cpp_objects.dir/build
.PHONY : common_cpp_objects/fast

#=============================================================================
# Target rules for targets named PureDoom

# Build rule for target.
PureDoom: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PureDoom
.PHONY : PureDoom

# fast build rule for target.
PureDoom/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PureDoom.dir/build.make CMakeFiles/PureDoom.dir/build
.PHONY : PureDoom/fast

#=============================================================================
# Target rules for targets named cuda_test_map

# Build rule for target.
cuda_test_map: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cuda_test_map
.PHONY : cuda_test_map

# fast build rule for target.
cuda_test_map/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuda_test_map.dir/build.make CMakeFiles/cuda_test_map.dir/build
.PHONY : cuda_test_map/fast

src/BSPTree.o: src/BSPTree.cpp.o
.PHONY : src/BSPTree.o

# target to build an object file
src/BSPTree.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common_cpp_objects.dir/build.make CMakeFiles/common_cpp_objects.dir/src/BSPTree.cpp.o
.PHONY : src/BSPTree.cpp.o

src/BSPTree.i: src/BSPTree.cpp.i
.PHONY : src/BSPTree.i

# target to preprocess a source file
src/BSPTree.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common_cpp_objects.dir/build.make CMakeFiles/common_cpp_objects.dir/src/BSPTree.cpp.i
.PHONY : src/BSPTree.cpp.i

src/BSPTree.s: src/BSPTree.cpp.s
.PHONY : src/BSPTree.s

# target to generate assembly for a file
src/BSPTree.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common_cpp_objects.dir/build.make CMakeFiles/common_cpp_objects.dir/src/BSPTree.cpp.s
.PHONY : src/BSPTree.cpp.s

src/CudaTestMap.o: src/CudaTestMap.cu.o
.PHONY : src/CudaTestMap.o

# target to build an object file
src/CudaTestMap.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuda_objects.dir/build.make CMakeFiles/cuda_objects.dir/src/CudaTestMap.cu.o
.PHONY : src/CudaTestMap.cu.o

src/CudaTestMap.i: src/CudaTestMap.cu.i
.PHONY : src/CudaTestMap.i

# target to preprocess a source file
src/CudaTestMap.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuda_objects.dir/build.make CMakeFiles/cuda_objects.dir/src/CudaTestMap.cu.i
.PHONY : src/CudaTestMap.cu.i

src/CudaTestMap.s: src/CudaTestMap.cu.s
.PHONY : src/CudaTestMap.s

# target to generate assembly for a file
src/CudaTestMap.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuda_objects.dir/build.make CMakeFiles/cuda_objects.dir/src/CudaTestMap.cu.s
.PHONY : src/CudaTestMap.cu.s

src/CudaUtils.o: src/CudaUtils.cu.o
.PHONY : src/CudaUtils.o

# target to build an object file
src/CudaUtils.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuda_objects.dir/build.make CMakeFiles/cuda_objects.dir/src/CudaUtils.cu.o
.PHONY : src/CudaUtils.cu.o

src/CudaUtils.i: src/CudaUtils.cu.i
.PHONY : src/CudaUtils.i

# target to preprocess a source file
src/CudaUtils.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuda_objects.dir/build.make CMakeFiles/cuda_objects.dir/src/CudaUtils.cu.i
.PHONY : src/CudaUtils.cu.i

src/CudaUtils.s: src/CudaUtils.cu.s
.PHONY : src/CudaUtils.s

# target to generate assembly for a file
src/CudaUtils.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuda_objects.dir/build.make CMakeFiles/cuda_objects.dir/src/CudaUtils.cu.s
.PHONY : src/CudaUtils.cu.s

src/Renderer.o: src/Renderer.cpp.o
.PHONY : src/Renderer.o

# target to build an object file
src/Renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common_cpp_objects.dir/build.make CMakeFiles/common_cpp_objects.dir/src/Renderer.cpp.o
.PHONY : src/Renderer.cpp.o

src/Renderer.i: src/Renderer.cpp.i
.PHONY : src/Renderer.i

# target to preprocess a source file
src/Renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common_cpp_objects.dir/build.make CMakeFiles/common_cpp_objects.dir/src/Renderer.cpp.i
.PHONY : src/Renderer.cpp.i

src/Renderer.s: src/Renderer.cpp.s
.PHONY : src/Renderer.s

# target to generate assembly for a file
src/Renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common_cpp_objects.dir/build.make CMakeFiles/common_cpp_objects.dir/src/Renderer.cpp.s
.PHONY : src/Renderer.cpp.s

src/RendererCuda.o: src/RendererCuda.cu.o
.PHONY : src/RendererCuda.o

# target to build an object file
src/RendererCuda.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuda_objects.dir/build.make CMakeFiles/cuda_objects.dir/src/RendererCuda.cu.o
.PHONY : src/RendererCuda.cu.o

src/RendererCuda.i: src/RendererCuda.cu.i
.PHONY : src/RendererCuda.i

# target to preprocess a source file
src/RendererCuda.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuda_objects.dir/build.make CMakeFiles/cuda_objects.dir/src/RendererCuda.cu.i
.PHONY : src/RendererCuda.cu.i

src/RendererCuda.s: src/RendererCuda.cu.s
.PHONY : src/RendererCuda.s

# target to generate assembly for a file
src/RendererCuda.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuda_objects.dir/build.make CMakeFiles/cuda_objects.dir/src/RendererCuda.cu.s
.PHONY : src/RendererCuda.cu.s

src/Sprite.o: src/Sprite.cpp.o
.PHONY : src/Sprite.o

# target to build an object file
src/Sprite.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common_cpp_objects.dir/build.make CMakeFiles/common_cpp_objects.dir/src/Sprite.cpp.o
.PHONY : src/Sprite.cpp.o

src/Sprite.i: src/Sprite.cpp.i
.PHONY : src/Sprite.i

# target to preprocess a source file
src/Sprite.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common_cpp_objects.dir/build.make CMakeFiles/common_cpp_objects.dir/src/Sprite.cpp.i
.PHONY : src/Sprite.cpp.i

src/Sprite.s: src/Sprite.cpp.s
.PHONY : src/Sprite.s

# target to generate assembly for a file
src/Sprite.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common_cpp_objects.dir/build.make CMakeFiles/common_cpp_objects.dir/src/Sprite.cpp.s
.PHONY : src/Sprite.cpp.s

src/TestMap.o: src/TestMap.cpp.o
.PHONY : src/TestMap.o

# target to build an object file
src/TestMap.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuda_test_map.dir/build.make CMakeFiles/cuda_test_map.dir/src/TestMap.cpp.o
.PHONY : src/TestMap.cpp.o

src/TestMap.i: src/TestMap.cpp.i
.PHONY : src/TestMap.i

# target to preprocess a source file
src/TestMap.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuda_test_map.dir/build.make CMakeFiles/cuda_test_map.dir/src/TestMap.cpp.i
.PHONY : src/TestMap.cpp.i

src/TestMap.s: src/TestMap.cpp.s
.PHONY : src/TestMap.s

# target to generate assembly for a file
src/TestMap.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuda_test_map.dir/build.make CMakeFiles/cuda_test_map.dir/src/TestMap.cpp.s
.PHONY : src/TestMap.cpp.s

src/TextureLoader.o: src/TextureLoader.cpp.o
.PHONY : src/TextureLoader.o

# target to build an object file
src/TextureLoader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common_cpp_objects.dir/build.make CMakeFiles/common_cpp_objects.dir/src/TextureLoader.cpp.o
.PHONY : src/TextureLoader.cpp.o

src/TextureLoader.i: src/TextureLoader.cpp.i
.PHONY : src/TextureLoader.i

# target to preprocess a source file
src/TextureLoader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common_cpp_objects.dir/build.make CMakeFiles/common_cpp_objects.dir/src/TextureLoader.cpp.i
.PHONY : src/TextureLoader.cpp.i

src/TextureLoader.s: src/TextureLoader.cpp.s
.PHONY : src/TextureLoader.s

# target to generate assembly for a file
src/TextureLoader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common_cpp_objects.dir/build.make CMakeFiles/common_cpp_objects.dir/src/TextureLoader.cpp.s
.PHONY : src/TextureLoader.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PureDoom.dir/build.make CMakeFiles/PureDoom.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PureDoom.dir/build.make CMakeFiles/PureDoom.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PureDoom.dir/build.make CMakeFiles/PureDoom.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... PureDoom"
	@echo "... common_cpp_objects"
	@echo "... cuda_objects"
	@echo "... cuda_test_map"
	@echo "... src/BSPTree.o"
	@echo "... src/BSPTree.i"
	@echo "... src/BSPTree.s"
	@echo "... src/CudaTestMap.o"
	@echo "... src/CudaTestMap.i"
	@echo "... src/CudaTestMap.s"
	@echo "... src/CudaUtils.o"
	@echo "... src/CudaUtils.i"
	@echo "... src/CudaUtils.s"
	@echo "... src/Renderer.o"
	@echo "... src/Renderer.i"
	@echo "... src/Renderer.s"
	@echo "... src/RendererCuda.o"
	@echo "... src/RendererCuda.i"
	@echo "... src/RendererCuda.s"
	@echo "... src/Sprite.o"
	@echo "... src/Sprite.i"
	@echo "... src/Sprite.s"
	@echo "... src/TestMap.o"
	@echo "... src/TestMap.i"
	@echo "... src/TestMap.s"
	@echo "... src/TextureLoader.o"
	@echo "... src/TextureLoader.i"
	@echo "... src/TextureLoader.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

